### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by devanshkv** [isazi/AOFlagger#1]
Hi!

We would like to use this package with our library called [your](https://github.com/thepetabyteproject/your). Can you please add a license?

Thanks!

**Comment by isazi** [comment]
I can add a license if you want, but this is basically just a toy project I have not touched in years. Our real-time code (already used in production within AMBER) is: https://github.com/TRASAL/RFIm

**Comment by devanshkv** [comment]
I was thinking about the CUDA implementation of the AOFlagger which is not available in [RFIm](https://github.com/TRASAL/RFIm), are there any plans of incorporating them within [RFIm](https://github.com/TRASAL/RFIm)?

**Comment by isazi** [comment]
If there is some interest. Let me license this code first. I will do it today.

**Comment by isazi** [comment]
Added the Apache license to the repository.

**Comment by devanshkv** [comment]
Awesome! Thank you so much.
